################################################################
##
## Mandatory settings for a DIRECTORY:
## - TOPDIR
## - SUBDIR
## - DIRECTORIES
##
## Available Make targets: 
## all [default], clean, headers, build
##
## Copyright (C) 2009-2013 Robin Klose
##
## This file is part of AVR3nk, available at 
## https://github.com/r3nk/AVR3nk
##
################################################################

################################################################
## Directory Settings
################################################################

TOPDIR := ..
SUBDIR := applications

DIRECTORIES := demo_cmdl
DIRECTORIES += demo_sensor
DIRECTORIES += CAN-inspector

################################################################
## Load Configuration
################################################################

include $(TOPDIR)/env/make/Make.conf
