################################################################
##
## Mandatory settings for a DIRECTORY:
## - TOPDIR
## - SUBDIR
## - DIRECTORIES
##
## Available Make targets: 
## all [default], clean, headers, build, install
##
## Copyright (C) 2009-2013 Robin Klose
##
## This file is part of AVR3nk, available at 
## https://github.com/r3nk/AVR3nk
##
################################################################

################################################################
## Directory Settings
################################################################

TOPDIR = ..
SUBDIR = subsystems

DIRECTORIES := cmdl

################################################################
## Load Configuration
################################################################

include $(TOPDIR)/env/make/Make.conf
